### ISSUE TITLE
Statis analysis reveals few problems

### ISSUE THREAD

**Issue by szepeviktor** [metorikhq/metorik-helper#90]
Hello!

`vendor/bin/phpstan analyze -l 4` static analysis powered by @phpstan reveals e.g. usage of legacy variables:
https://docs.woocommerce.com/wc-apidocs/source-class-WC_Legacy_Cart.html#67-169
and other problems.

I've just implemented package stubs for WC:
1. https://github.com/php-stubs/woocommerce-stubs/blob/master/woocommerce-packages-stubs.php
1. https://github.com/php-stubs/woocommerce-stubs/blob/master/woocommerce-stubs.php

Please use these 2 files.
You may want to use older WC stubs: https://github.com/php-stubs/woocommerce-stubs/releases
although packages are not released before 3.8.0 - you may generate them easily by `./generate.sh`

`composer.json`

```json
{
    "require-dev": {
        "szepeviktor/phpstan-wordpress": "^0.5.0"
    },
    "autoload": {
        "classmap": [
            "inc/"
        ]
    }
}
```

`phpstan.neon.dist`

```yaml
includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - metorik-helper.php
        - inc/
    autoload_files:
#        - %rootDir%/../../php-stubs/woocommerce-stubs/woocommerce-stubs.php
#        - %rootDir%/../../php-stubs/woocommerce-stubs/woocommerce-packages-stubs.php
        - woocommerce-stubs.php
        - woocommerce-packages-stubs.php
        - metorik-helper.php
        - inc/functions.php
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters(_ref_array)? invoked with [34567] parameters, 2 required\.$#'
```
